{{- if and .Values.frontend.enabled .Values.route.enabled -}}
{{- $cloudProviderFlavor := default .Values.global.cloudProvider.flavor .Values.cloudProvider.flavor -}}
{{- if eq $cloudProviderFlavor "openshift" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "metatile-queue-populator-ui.frontend.fullname" . }}
  labels:
    {{- include "metatile-queue-populator-ui.labels" . | nindent 4 }}
    {{- include "metatile-queue-populator-ui.frontend.selectorLabels" . | nindent 4 }}
spec:
  path: {{ .Values.route.path | default "/" }}
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "metatile-queue-populator-ui.frontend.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  {{- end }}
{{- end }}
{{- end }}
