{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default (printf "%s-secret" (include "metatile-queue-populator-ui.fullname" .)) }}
  labels:
    {{- include "metatile-queue-populator-ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.rasterToken }}
  token: {{ .Values.secrets.rasterToken | quote }}
  {{- end }}
  {{- if .Values.secrets.dbUsername }}
  db-username: {{ .Values.secrets.dbUsername | quote }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.appDbUsername }}
  app-db-username: {{ .Values.secrets.appDbUsername | quote }}
  {{- end }}
  {{- if .Values.secrets.appDbPassword }}
  app-db-password: {{ .Values.secrets.appDbPassword | quote }}
  {{- end }}
{{- end }}
