packages:
  - 'apps/*'

onlyBuiltDependencies:
  - '@scarf/scarf'
  - 'protobufjs'
  - 'unrs-resolver'
  - '@swc/core'
  - 'esbuild'

allowBuilds:
  '@scarf/scarf': false
  esbuild: false
  protobufjs: false
  unrs-resolver: false
