{{- if .Values.backend.enabled -}}
{{- $registryUrl := include "metatile-queue-populator-ui.cloudProviderDockerRegistryUrl" . -}}
{{- $imagePullSecret := include "metatile-queue-populator-ui.cloudProviderImagePullSecretName" . -}}
{{- $chartSecretName := .Values.secrets.name | default (printf "%s-secret" (include "metatile-queue-populator-ui.fullname" .)) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metatile-queue-populator-ui.backend.fullname" . }}
  labels:
    {{- include "metatile-queue-populator-ui.labels" . | nindent 4 }}
    {{- include "metatile-queue-populator-ui.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  revisionHistoryLimit: {{ .Values.backend.revisionHistoryLimit | default .Values.revisionHistoryLimit | default 2 }}
  selector:
    matchLabels:
      {{- include "metatile-queue-populator-ui.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metatile-queue-populator-ui.labels" . | nindent 8 }}
        {{- include "metatile-queue-populator-ui.backend.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
        {{- if .Values.secrets.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- if $imagePullSecret }}
      imagePullSecrets:
        - name: {{ $imagePullSecret | quote }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: backend
          image: {{ $registryUrl }}{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort | default 8080 }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: CONFIG_OFFLINE_MODE
              value: "true"
            - name: TELEMETRY_TRACING_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: {{ .Values.backend.service.targetPort | default 8080 | quote }}
            {{- if or .Values.secrets.enabled .Values.backend.env.raster.tokenSecretName }}
            - name: RASTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default $chartSecretName .Values.backend.env.raster.tokenSecretName }}
                  key: {{ default "token" .Values.backend.env.raster.tokenSecretKey }}
            {{- end }}
            {{- if or .Values.secrets.enabled .Values.backend.env.appDb.secretName }}
            - name: APP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default $chartSecretName .Values.backend.env.appDb.secretName }}
                  key: {{ if .Values.secrets.enabled }}{{ default "app-db-username" .Values.backend.env.appDb.usernameKey }}{{ else }}{{ default "username" .Values.backend.env.appDb.usernameKey }}{{ end }}
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default $chartSecretName .Values.backend.env.appDb.secretName }}
                  key: {{ if .Values.secrets.enabled }}{{ default "app-db-password" .Values.backend.env.appDb.passwordKey }}{{ else }}{{ default "password" .Values.backend.env.appDb.passwordKey }}{{ end }}
            {{- end }}
            {{- if or .Values.secrets.enabled .Values.backend.env.db.secretName }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default $chartSecretName .Values.backend.env.db.secretName }}
                  key: {{ if .Values.secrets.enabled }}{{ default "db-username" .Values.backend.env.db.usernameKey }}{{ else }}{{ default "username" .Values.backend.env.db.usernameKey }}{{ end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default $chartSecretName .Values.backend.env.db.secretName }}
                  key: {{ if .Values.secrets.enabled }}{{ default "db-password" .Values.backend.env.db.passwordKey }}{{ else }}{{ default "password" .Values.backend.env.db.passwordKey }}{{ end }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/apps/server/dist/config/default.json
              subPath: default.json
            {{- if .Values.backend.env.appDb.ssl.secretName }}
            - name: app-db-certs
              mountPath: /etc/pki/app-db
              readOnly: true
            {{- end }}
            {{- if .Values.backend.env.db.ssl.secretName }}
            - name: db-certs
              mountPath: /etc/pki/db
              readOnly: true
            {{- end }}
          {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.backend.resources.enabled }}
          resources:
            {{- toYaml .Values.backend.resources.value | nindent 12 }}
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "metatile-queue-populator-ui.backend.fullname" . }}-config
        {{- if .Values.backend.env.appDb.ssl.secretName }}
        - name: app-db-certs
          secret:
            secretName: {{ .Values.backend.env.appDb.ssl.secretName }}
        {{- end }}
        {{- if .Values.backend.env.db.ssl.secretName }}
        - name: db-certs
          secret:
            secretName: {{ .Values.backend.env.db.ssl.secretName }}
        {{- end }}
{{- end }}
