{{- if .Values.discovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metatile-queue-populator-ui.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metatile-queue-populator-ui.labels" . | nindent 4 }}
    {{- include "metatile-queue-populator-ui.backend.selectorLabels" . | nindent 4 }}
{{- end }}
